import numpy as np

#Reminder
a = np.arange(20).reshape(4,5)
print(a)
print(a[3,2])
print("\n")
b = np.array([5,10,3,8,12,54,2,9,63])
print(b)
print("\nSorting")
print(np.sort(b))
print("\nPower")
print(np.power(b,2))
print("\nAnother way to power up numbers")
print(np.array(b**2))
print("\nClassifying")
print(np.array(b>=20))
print("Min n Max")
print(np.array(b.min()))
print(np.array(b.max()))
print("Concatenation")
c = np.array([2,3,4,5])
d = np.array([7,8,10,14])
print(np.concatenate((c,d)))

x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9]])
print(x+y)
print(np.add(x,y))
